version: '3'
services:
    app:
      environment:
        - SLACK_APP_TOKEN=<slack_app_token>
        - SLACK_BOT_TOKEN=<slack_bot_token>
        - SC_TOKEN=<statuscake_api_token>
        - SCBOT_ENV=dev
        - DB_HOST=db
        - DB_USER=db_user
        - DB_PASS=db_pass
        - DB_PORT=3306
        - DB_NAME=db_name
      build:
        context: ./
        dockerfile: Dockerfile
      image: scbot
      stdin_open: true
      tty: true
      depends_on:
        - scbot-db

    db:
      image: 'mariadb:10.7.1-focal'
      volumes:
        - ./db_data:/var/lib/mysql
      environment:
        MARIADB_ROOT_PASSWORD: 'root_pass'
        MARIADB_DATABASE: 'db_name'
        MARIADB_USER: 'db_name'
        MARIADB_PASSWORD: 'db_pass'
      stdin_open: true
      tty: true