before_script:
  - date -u
after_script:
  - date -u
variables:
  GIT_STRATEGY: clone

stages:
  - test
  - build

## actually push a tagged version of the chart
tagged:
  rules:
    - if: $CI_COMMIT_TAG
  tags:
    - docker
  stage: build
  image: git.liquidweb.com:4567/packaging/dockerfiles:helm
  script:
    - helm repo add $repo_url --username $repo_username --password $repo_password
    - helm push . $repo_url 

## do a test build of the chart
latest:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker
  stage: test
  image: git.liquidweb.com:4567/packaging/dockerfiles:helm
  script:
    - helm lint
    - helm package .
  # before_script:
  #   - env
  #   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  # script:
  #   - docker run -v $PWD:/usr/src/chart --entrypoint "" git.liquidweb.com:4567/mako/helmpack:v1.2.2 helm lint
