ingress:
  enabled: false

databaseHostEnvVar: DB_HOST
env:
  - name: "SLACK_APP_TOKEN"
    value: "xapp-1-A02TW25TPGD-3010326584051-f7fd78c9a2f44c816f58009090b29900cd2cc87d95533d50ae81bd1cefab02ee"
  - name: "SLACK_BOT_TOKEN"
    value: "xoxb-2151910542-3028333584976-km5wZLfPawFUY6ROVT5SIku7"
  - name: "SLACK_SIGN_SECRET"
    value: "0ed3fe53a74fe74ca889a228eaa84265"
  - name: "SC_TOKEN"
    value: "EB6vCR7t0aSzFdgNcOfA4W3PMGZY5T"
  - name: "SCBOT_ENV"
    value: "dev"
  - name: "DB_USER"
    value: "scbot"
  - name: "DB_NAME"
    value: "statuscake_bot"
  - name: "DB_PASS"
    value: "SemiviscidWatchbandsHamletsNisula6382"
  - name: "DB_PORT"
    value: 3306

database:
  env:
    - name: MARIADB_USER
      value: "scbot"
    - name: MARIADB_ROOT_PASSWORD
      value: "FlenchingFajitaSangahMesoplodont3502"
    - name: MARIADB_PASSWORD
      value: "SemiviscidWatchbandsHamletsNisula6382"
    - name: MARIADB_DATABASE
      value: "statuscake_bot"
  claimName: "mariadb-storage"
